### ISSUE TITLE
data.aws_vpc.peer_src_vpc.tags does not have homogenous types

### ISSUE THREAD

**Issue by messiahUA** [cloudposse/terraform-aws-vpc-peering#11]
Trying to connect kops created VPC with manual one:

> At column 33, line 1: map "data.aws_vpc.peer_src_vpc.tags" does not have homogenous types. found TypeString and then TypeMap in:
> 
> ${data.aws_vpc.peer_src_vpc.tags["Name"]} to ${data.aws_vpc.peer_dst_vpc.tags["Name"]}

**Comment by aknysh** [comment]
@messiahUA 
take a look at this module https://github.com/cloudposse/terraform-aws-kops-vpc-peering
it uses https://github.com/cloudposse/terraform-aws-kops-metadata to lookup the kops VPC

also some examples here:
https://github.com/cloudposse/terraform-root-modules/blob/master/aws/eks-backing-services-peering/main.tf

**Comment by messiahUA** [comment]
@aknysh thanks for reply, but actually I somehow posted an issue for the wrong repository. I'm sorry.
