### ISSUE TITLE
Count errors in latest release and master

### ISSUE THREAD

**Issue by TGWolf** [cloudposse/terraform-aws-vpc-peering#18]
Error: Invalid count argument

  on .terraform/modules/vpc.vpc_peering/main.tf line 62, in resource "aws_route" "requestor":
  62:   count                     = var.enabled ? length(distinct(sort(data.aws_route_tables.requestor.0.ids))) * length(data.aws_vpc.acceptor.0.cidr_block_associations) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

Error: Invalid count argument

  on .terraform/modules/vpc.vpc_peering/main.tf line 71, in resource "aws_route" "acceptor":
  71:   count                     = var.enabled ? length(distinct(sort(data.aws_route_tables.acceptor.0.ids))) * length(data.aws_vpc.requestor.0.cidr_block_associations) : 0

**Comment by Stratouklos** [comment]
Expressing this with `for_each` results in the same error

**Comment by aaronclong** [comment]
I am having the same problem. Likewise, I can't apply my terraform scripts because of this issue:

![image](https://user-images.githubusercontent.com/7354981/76633434-163f7000-651b-11ea-8730-ef0b92d894c6.png)

**Comment by aaronclong** [comment]
I think this might be the same issue in another module: https://github.com/grem11n/terraform-aws-vpc-peering/issues/49

**Comment by XiaobingBenYu** [comment]
any updates?

**Comment by rafilkmp3** [comment]
Its still happening

**Comment by rafilkmp3** [comment]
@TGWolf  this should reopened

**Comment by pj0620** [comment]
I fixed this issue by, as noted in the error message, using the -target argument. You are using it in apply it should be used in plan.

terraform plan -target="module.<MODULE TO BE PLANNED FIRST>"
